spring:
    application:
        name: gestionEcole
    config:
        activate:
            on-profile: dev # Active ce profil lorsque 'dev' est le profil actif
    main:
        allow-bean-definition-overriding: true

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/archivageEcole?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: archivage # <--- TRÈS IMPORTANT : Remplacez par votre nom d'utilisateur MySQL local
        password: passer # <--- TRÈS IMPORTANT : Remplacez par votre mot de passe MySQL local
        hikari:
            poolName: Hikari
            auto-commit: false # Important pour la gestion des transactions JPA

    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect # Dialecte Hibernate pour MySQL 8+
        hibernate:
            # IMPORTANT : En JHipster, Liquibase gère le schéma.
            # Mettez 'none' pour éviter que Hibernate ne tente de modifier la base de données directement,
            # ce qui peut causer des conflits avec Liquibase.
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    jackson:
        afterburner:
            enabled: false

    liquibase:
        change-log: classpath:config/liquibase/master.xml
        # IMPORTANT : Cette ligne va SUPPRIMER toutes les tables de votre base de données 'newArchiveApp'
        # à chaque démarrage de l'application en mode 'dev'.
        # Utilisez-la UNIQUEMENT en développement pour garantir un état propre.
        # Ne jamais utiliser en production !
        drop-first: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: abdalahtims@gmail.com
        password: otsduwzjlhflebio
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true

server:
    port: 8082

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /v3/api-docs

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include:
                    - configprops
                    - env
                    - health
                    - info
                    - logfile
                    - loggers
                    - prometheus
                    - threaddump
                    - liquibase
    endpoint:
        health:
            show-details: when_authorized
            roles: 'ROLE_ADMIN'
    info:
        git:
            mode: full
    prometheus:
        metrics:
            export:
                enabled: true
                step: 60

info:
    display-ribbon-on-profiles: 'dev'

jhipster:
    clientApp:
        name: 'gestionEcole'
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    mail:
        from: gestionEcole@localhost
    logging:
        use-json-format: false
        logstash:
            enabled: false
            host: localhost
            port: 5000
            ring-buffer-size: 512
    security:
        authentication:
            jwt:
                base64-secret: dm90cmUtc3VwZXItY2xlLXNlY3JldGUtcXVpLWRvaXQtZXRyZS1sb25ndWUtYXUtbW9pbnMtMzItY2FyYWN0ZXJlcy1wb3VyLWxhLXNlY3VyaXRlCg==
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000

#  metrics:
#    logs:
##      enabled: false
##      report-frequency: 60 # in seconds
